### ISSUE TITLE
Replace HashableModel with UUID field

### ISSUE THREAD

**Issue by jpic** [political-memory/django-representatives#6]
This issue advocates for complete removal of all code that's related to HashableModel. We could still provide a unique id using django 1.8's UUIDField, but the database would be doing the work, not python: https://github.com/political-memory/django-representatives/blob/master/representatives/models.py#L58-L70

If there's no reason to keep it, i'll be able to work on in it December.

**Comment by jpic** [comment]
I'll just not care about it for now.

**Comment by luxcem** [comment]
The idea of HashableModel was to provide a way to identify a unique model to avoid importing it twice.
The idea was that if a model shared common properties with an other it should be treated as a duplicate, those properties would be represented as the hash value. I thought about the UUID field for a bit, but I though it was less customisable as HashableModel is.
